const TypeAction = {
    AUTH_LOGIN: 'AUTH_LOGIN',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    AUTH_REGISTER: 'AUTH_REGISTER',
    AUTH_CHECK: 'AUTH_CHECK',
    GET_COMMENT: 'GET_COMMENT',
    ADD_COMMENT: 'ADD_COMMENT',
    ADD_REPLY_COMMENT: 'ADD_REPLY_COMMENT',
    GET_SEARCH: 'GET_SEARCH',
    ADD_SEARCH: 'ADD_SEARCH',
    DEL_SEARCH: 'DEL_SEARCH',
    GET_USER: 'GET_USER',
    GET_ALL_USER: 'GET_ALL_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
};
export default TypeAction;
