const routes = {
    Home: '/',
    // Home: '/galaxyplay_ui',
    WareHouse: '/browse',
    Movie: '/browse/movie',
    Player: '/player',
    PlayerUrl: '/player/*',
    InfoMovie: '/info/movie',
    InfoMovieUrl: '/info/movie/*',
    PhimDienAnh: '/browse/movie',
    PhimDienAnhSearch: '/browse/movie/search',
    PhimBo: '/browse/tvseries',
    PhimThue: '/browse/rental',
    PhimThueSearch: '/browse/rental/search',
    Blog: '/blog',
    Help: '/help',
    Search: '/search',
    Login: '/login',
    Logout: '/logout',
    Register: '/register',
    UserManager: '/admin/user-manager',
    Account: '/account',
};
export default routes;
